// FROM part4-code:p499

// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#ifndef _TPM_INCLUDE_PUBLIC_BASETYPES_H_
#define _TPM_INCLUDE_PUBLIC_BASETYPES_H_

// NULL definition
#ifndef NULL
#  define NULL ((void*)0)
#endif  // NULL

// typedef uint8_t  UINT8;
// typedef uint8_t  BYTE;
// typedef int8_t   INT8;
// typedef int      BOOL;
// typedef uint16_t UINT16;
// typedef int16_t  INT16;
// typedef uint32_t UINT32;
// typedef int32_t  INT32;
// typedef uint64_t UINT64;
// typedef int64_t  INT64;
typedef unsigned char          UINT8;
typedef unsigned short         UINT16;
typedef unsigned int           UINT32;
typedef signed char            INT8;
typedef signed short           INT16;
typedef signed int             INT32;
typedef unsigned int           BOOL;
typedef uint8_t  BYTE;
typedef unsigned long long     UINT64;
typedef signed long long       INT64;



#endif  // _TPM_INCLUDE_PUBLIC_BASETYPES_H_
