// FROM part4-code:p479

// FILE GENERATED BY TpmExtractCode: DO NOT EDIT
#if CC_StartAuthSession // Command must be enabled

#ifndef _TPM_INCLUDE_PRIVATE_PROTOTYPES_STARTAUTHSESSION_FP_H_
#define _TPM_INCLUDE_PRIVATE_PROTOTYPES_STARTAUTHSESSION_FP_H_

// Input structure definition
typedef struct
{
    TPMI_DH_OBJECT tpmKey;                  // 解密密钥的（对象）句柄
    TPMI_DH_ENTITY bind;                    // 绑定对象的（实体）句柄
    TPM2B_NONCE nonceCaller;                // 调用方提供的随机数
    TPM2B_ENCRYPTED_SECRET encryptedSalt;   // 加密的盐值
    TPM_SE sessionType;                     // 会话类型（HMAC、策略或加密）
    TPMT_SYM_DEF symmetric;                 // 指定算法
    TPMI_ALG_HASH authHash;                 // 
} StartAuthSession_In;

// Output structure definition
typedef struct
{
    TPMI_SH_AUTH_SESSION sessionHandle; // 新生成的会话句柄
    TPM2B_NONCE nonceTPM;               // TPM 生成的随机数
} StartAuthSession_Out;

// Response code modifiers
#define RC_StartAuthSession_tpmKey (TPM_RC_H + TPM_RC_1)
#define RC_StartAuthSession_bind (TPM_RC_H + TPM_RC_2)
#define RC_StartAuthSession_nonceCaller (TPM_RC_P + TPM_RC_1)
#define RC_StartAuthSession_encryptedSalt (TPM_RC_P + TPM_RC_2)
#define RC_StartAuthSession_sessionType (TPM_RC_P + TPM_RC_3)
#define RC_StartAuthSession_symmetric (TPM_RC_P + TPM_RC_4)
#define RC_StartAuthSession_authHash (TPM_RC_P + TPM_RC_5)

// Function prototype
TPM_RC
TPM2_StartAuthSession(StartAuthSession_In *in, StartAuthSession_Out *out);

#endif // _TPM_INCLUDE_PRIVATE_PROTOTYPES_STARTAUTHSESSION_FP_H_
#endif // CC_StartAuthSession